baseURL = "https://ozozozd.github.io/vibelexity-blog/"
languageCode = "en-us"
title = "Terminal"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false

[params.twitter]
  creator = ""
  site = ""

[languages.en]
  languageName = "English"
  title = "Terminal"
  subtitle = "A simple, retro theme for Hugo"
  owner = ""
  keywords = ""
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  dateFormat = "2006-01-02"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "showcase"
      name = "Showcase"
      url = "/showcase"
